name: Push the code from dev to prod

on: 
  workflow_dispatch

jobs:
  migrate:
    if: contains('["kcwong395"]', github.actor)
    runs-on: ubuntu-latest
    name: Migrate code from dev branch to prod
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
        
      - name: check path and files
        run: ls -al && pwd
        
      - name: Push
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './'
          destination-github-username: 'kcwong395'
          destination-repository-name: 'job-hook'
          user-email: kcwong395@gmail.com
          target-branch: prod
